language: shell

os: linux
dist: focal

addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
  - pip3 install -U pip
  - pip3 install setuptools
  - pip3 install vim-vint
  - pip3 install flake8

script:
  - ./test
