language: shell

os: linux
dist: focal  # for python3.8 (https://packages.ubuntu.com/en/focal/python3)

addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
  - pip3 install -U pip
  - pip3 install setuptools
  - pip3 install -r requirements-dev.txt

script:
  - ./test
